export const GET_AIRLINES = "GET_AIRLINES";
export const GET_DETAILS = "GET_DETAILS";
export const GET_AIRLINE_FLIGHTS = 'GET_AIRLINE_FLIGHTS';
export const UPDATE_AIRLINE = "UPDATE_AIRLINE";
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_FLIGHT = 'CREATE_FLIGHT';
